### ISSUE TITLE
Criar adapter de meio de pagamentos (gateway)

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#10]
Criar adapter para o [omnipay](http://omnipay.thephpleague.com/) para os seguinte gateways de pagamento:

MercadoPago
PagSeguro
Moip 

Já existem vários adapters criados no projeto, mas a maioria americano. Essa colaboração já será também uma colaboração para o projeto do Omnipay. :)

**Comment by victorximenis** [comment]
Posso pegar essa issue. Curti a ideia.

**Comment by abdala** [comment]
Adicionei a integração com o PagSeguro:

https://github.com/abdala/omnipay-pagseguro

``` javascript
{
    "require": {
        "abdala/omnipay-pagseguro": "~1.0"
    }
}
```

**Comment by jfmelo** [comment]
@abdala você chegou a ver esses adapters:
- [MercadoPago](https://github.com/victorximenis/omnipay-mercadopago)
- [Moip](https://github.com/bavarianlabs/omnipay-moip)

**Comment by abdala** [comment]
@dudemelo: o do MercadoPago foi feito pelo @victorximenis. Acredito que falta só ele publicar no Packagist. O do Moip ainda não foi feito.

https://github.com/victorximenis/omnipay-mercadopago

**Comment by victorximenis** [comment]
Isso, só tá faltando o packagist
