### ISSUE TITLE
Criar integração do omnipay

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#11]
Utilizar os adapters criados no issue #10 para integrar os meios de pagamento

Referência
http://omnipay.thephpleague.com

**Comment by AyrtonRicardo** [comment]
Curti a ideia, posso pegar essa issue!

**Comment by isaachbn** [comment]
Tamo junto @AyrtonRicardo , vou ajudar da Issue.

**Comment by abdala** [comment]
@AyrtonRicardo e @isaachbn, como está isso? Vcs viram que tem um tempo que terminei o gateway do PagSeguro, né?

https://github.com/abdala/omnipay-pagseguro
