### ISSUE TITLE
Criação das interfaces

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#2]
Criar interfaces(html/css/js) baseadas nos wireframes apresentados no #1

**Comment by brunnohofmann** [comment]
Pretende-se utilizer alguma template pra isso?
Em termos de framework tem o Material Design, bem bacana.
(eu não participei da primeira reunião, então me perdoem se já tiverem definido algo) :D

**Comment by abdala** [comment]
Vamos deixar a escolha livre para quem for pegar. :)

**Comment by alustau** [comment]
Concordo em usar o Material Design, acho muito legal!

**Comment by joepreludian** [comment]
Parceiros!  Essa interface de template já foi pensada? Que tal se utilizar AngularJS como sistema de backend? Abraços!

**Comment by abdala** [comment]
@brunnohofmann, @joepreludian acho interessante também. ;) #labs

**Comment by abdala** [comment]
@brunnohofmann @joffilyfe vcs podem ficar com esse issue?

**Comment by abdala** [comment]
Olhar o issue #1 para referência das telas

**Comment by franklinrabay** [comment]
@brunnohofmann @joffilyfe, vocês vão ficar com essa tarefa?

**Comment by joffilyfe** [comment]
@franklinrabay Eu gostaria de contrinuir sim, vamos fazer um pair?

**Comment by brunnohofmann** [comment]
Bora simbora intão!!!!

**Comment by franklinrabay** [comment]
Então galera, vamo usar o Material Angular, https://material.angularjs.org/latest/ 
Ele já tem muita diretiva pra usar, é muito prático.

Amanha as 22 estaremos dando o pontapé inicial nas atividades, posso contar com vocês?
