### ISSUE TITLE
Definir modelagem de banco que será utilizada

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#3]
Criar a estrutura inicial de documentos que será utilizado no MongoDB

**Comment by abdala** [comment]
Essa é a modelagem dos documentos e seus relacionamentos.

Segue o link para referência de Embed e Reference:
http://docs.mongodb.org/manual/core/data-modeling-introduction/

![mongodb](https://cloud.githubusercontent.com/assets/219340/9419003/70f33540-482e-11e5-8d30-14798cb2600e.png)

**Comment by malukenho** [comment]
@abdala acho que já poderiam ir criando as entidades referentes a usuário e evento

**Comment by abdala** [comment]
@malukenho Perfeito! Está engatilhado. Postei isso para não criar sem discutir. ;) O que achou? Estou com medo de ser difícil listar todas as ordens de um evento...

**Comment by malukenho** [comment]
@abdala a intenção é fazer um _event stroming_?
