### ISSUE TITLE
Criar/padronizar o ambiente de desenvolvimento (Vagrant/ansible)

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#4]
Definir e criar os arquivos de configuração para padronização do ambiente de desenvolvimento

Ferramentas:
PHP 5.6
Ngnix
MongoDB
Redis

Referências:
http://phansible.com
https://www.vagrantup.com
http://www.ansible.com/home

**Comment by alustau** [comment]
O ambiente fica a escolha de quem vai criar?

**Comment by abdala** [comment]
@Alustau dei um update aí no issue :)

**Comment by alustau** [comment]
Top! Eu fico com esta issue!
