### ISSUE TITLE
Postar os resultados da pesquisa de framework

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#5]
Tinhamos conversado sobre pesquisar, testar e definir qual o framework será utilizado. Postar os resultados e argumentos aqui.

**Comment by malukenho** [comment]
@abdala seria legal se fizéssemos algo usando `CQRS + Event Sourcing` :+1:

**Comment by abdala** [comment]
@malukenho acho super válido. Vc tomaria a frente disso?

**Comment by jfmelo** [comment]
**MongoDB ODM**

Além da facilidade para adicionar/configurar, é muito parecido com o ORM. O único ponto negativo é que não possui o gerador de entidades (documentos no caso) e formulários.
- [DoctrineMongoDBBundle](http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html)
- [Doctrine MongoDB ODM](http://doctrine-mongodb-odm.readthedocs.org/en/latest/)

**Symfony HWIOauth**
- [Symfony Security](http://symfony.com/doc/current/book/security.html)
- [HWIOAuthBundle](https://github.com/hwi/HWIOAuthBundle/tree/master/Resources/doc)

**Omnipay**
- [Omnipay](https://github.com/thephpleague/omnipay)
- [PayumBundle](https://github.com/Payum/PayumBundle/tree/master/Resources/doc)
