### ISSUE TITLE
Criar estrutura inicial do projeto

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#6]
Criar a estrutura inicial do projeto utilizando a framework definida no issue #5

**Comment by joepreludian** [comment]
Posso dar uma sugestão? Recomendo, fortemente, utilizarmos o PHP como um serviço RESTFull, sendo consumido por uma aplicação de uma página só, que seria o angular. Só assim facilitaria bastante o projeto, o tornando testável.

**Comment by joepreludian** [comment]
Recomendo descrever o processo do aplicativo, como você imagina, através dessa ferramenta:
https://www.draw.io/

Ao menos o a forma como voce quer que o processo ocorre. Acho que ajuda a direcionar melhor, não?
Abraço!

**Comment by alustau** [comment]
Na primeira reunião foi discutido que iam ter duas frentes pra se decidir qual estrutura irá ser utilizada neste projeto, @joepreludian. Uma frente irá usar laravel/lumen e a outra frente irá usar Symphony. Cada frente tem que abordar 3 topicos principais: 
1 - Integração com Omnipay;
2 - Integração com as redes sociais (oAuth);
3 - Integraçao com MongoDb - Redis;

O prazo pra ser definido será sexta-feira (21/08/2015).
Mas nada impede de se montar uma frente  com essa estrutura que voce sugeriu. A ideia desse projeto é trabalhar com novas tecnologias afim de aprendizado, e claro tornar este projeto um sucesso e disponibilizando para todos aqueles que quiserem contribuir e usar. Seria interessante você aparecer amanhã na reunião para nos ajudar a definir.
