### ISSUE TITLE
Criar canal no slack ou telegram ou gitter

### ISSUE THREAD

**Issue by abdala** [PHPeste/conticket#8]
Criar e divulgar um canal em uma das ferramentas para centralizar a comunicação da equipe.

**Comment by jefflssantos** [comment]
Mande seu email para o convite ser enviado.
https://jefflssantos.typeform.com/to/ZvX0Fx

**Comment by jefflssantos** [comment]
link para entrar no slack https://phpeste-slack.herokuapp.com/
